  export const products = [
    {
      id: "1",
      name: "Mobile A",
      price: "$300",
      rating: 4,
      details: "This smartphone is designed for those who demand performance and reliability.",
      reviews: ["Great product", "Good value for money"],
      description: "This smartphone is designed for those who demand performance and reliability. Powered by the latest processor and backed with ample RAM, it handles multitasking effortlessly. The vibrant display delivers crisp visuals, while the high-resolution camera captures stunning photos in any lighting condition. Whether you’re a gamer, a content creator, or just need a reliable device for daily use, this mobile phone is built to exceed expectations.",
      category: "Electronics",
      brand: "Brand A",
      inStock: true,
      image: "/images/img1.jpg",
      images: ['/images/mbl2.jpg', '/images/img1.jpg', '/images/mbl2.jpg', '/images/img1.jpg'],
      vendor: {
        id: "101",
        name: "Samsung",
        location: "Hyderabad",
        image: "/images/img1.jpg",
      },
  
    },
    {
      id: "2",
      name: "Mobile B",
      price: "$200",
      rating: 4.5,
      details:"Powered by the latest processor and backed with ample RAM, it handles multitasking effortlessly.",
      reviews: ["Great product", "Good value for money"],
      description: "This smartphone is designed for those who demand performance and reliability. Powered by the latest processor and backed with ample RAM, it handles multitasking effortlessly. The vibrant display delivers crisp visuals, while the high-resolution camera captures stunning photos in any lighting condition. Whether you’re a gamer, a content creator, or just need a reliable device for daily use, this mobile phone is built to exceed expectations.",
      category: "Electronics",
      brand: "Brand A",
      inStock: false,
      image: "/images/img1.jpg",
      images: ['/images/img1.jpg', '/images/img2.jpg', '/images/img1.jpg', '/images/img2.jpg'],
      vendor: {
        id: "102",
        name: "Apple",
        location: "Vijayawada",
        image: "/images/img1.jpg",
      },
    },
    {
      id: "3",
      name: "Mobile C",
      price: "$200",
      rating: 5,
      details: "Powered by the latest processor and backed with ample RAM, it handles multitasking effortlessly.",
      reviews: ["Great product", "Good value for money"],
      description: "This smartphone is designed for those who demand performance and reliability. Powered by the latest processor and backed with ample RAM, it handles multitasking effortlessly. The vibrant display delivers crisp visuals, while the high-resolution camera captures stunning photos in any lighting condition. Whether you’re a gamer, a content creator, or just need a reliable device for daily use, this mobile phone is built to exceed expectations.",
      category: "Electronics",
      brand: "Brand A",
      inStock: true,
      image: "/images/img1.jpg",
      images: ['/images/img3.jpg', '/images/img2.jpg', '/images/img3.jpg', '/images/img2.jpg'],
      vendor: {
        id: "101",
        name: "Samsung",
        location: "Hyderabad",
        image: "/images/img1.jpg",
      },
    },
    {
      id: "4",
      name: "Mobile A",
      price: "$800",
      rating: 3.5,
      details:"This smartphone is designed for those who demand performance and reliability.",
      reviews: ["Great product", "Good value for money"],
      description: "This smartphone is designed for those who demand performance and reliability. Powered by the latest processor and backed with ample RAM, it handles multitasking effortlessly. The vibrant display delivers crisp visuals, while the high-resolution camera captures stunning photos in any lighting condition. Whether you’re a gamer, a content creator, or just need a reliable device for daily use, this mobile phone is built to exceed expectations.",
      category: "Electronics",
      brand: "Brand A",
      inStock: true,
      image: "/images/img1.jpg",
      images: ['/images/img3.jpg', '/images/img1.jpg', '/images/img3.jpg', '/images/img1.jpg'],
      vendor: {
        id: "104",
        name: "Vivo",
        location: "Vizag",
        image: "/images/img1.jpg",
      },
    },
    {
      id: "5",
      name: "Mobile B",
      price: "$500",
      rating: 4,
      details: "Powered by the latest processor and backed with ample RAM, it handles multitasking effortlessly.",
      reviews: ["Great product", "Good value for money"],
      description: "This smartphone is designed for those who demand performance and reliability. Powered by the latest processor and backed with ample RAM, it handles multitasking effortlessly. The vibrant display delivers crisp visuals, while the high-resolution camera captures stunning photos in any lighting condition. Whether you’re a gamer, a content creator, or just need a reliable device for daily use, this mobile phone is built to exceed expectations.",
      category: "Electronics",
      brand: "Brand A",
      inStock: true,
      image: "/images/img2.jpg",
      images: ['/images/img2.jpg', '/images/img1.jpg', '/images/img2.jpg', '/images/img1.jpg'],
      vendor: {
        id: "107",
        name: "Vivo",
        location: "Hyderabad",
        image: "/images/img2.jpg",
      },
    },
    {
      id: "6",
      name: "Mobile C",
      price: "$300",
      rating: 4.5,
      details: "This smartphone is designed for those who demand performance and reliability.",
      reviews: ["Great product", "Good value for money"],
      description: "This smartphone is designed for those who demand performance and reliability. Powered by the latest processor and backed with ample RAM, it handles multitasking effortlessly. The vibrant display delivers crisp visuals, while the high-resolution camera captures stunning photos in any lighting condition. Whether you’re a gamer, a content creator, or just need a reliable device for daily use, this mobile phone is built to exceed expectations.",
      category: "Electronics",
      brand: "Brand A",
      inStock: false,
      image: "/images/img1.jpg",
      images: ['/images/img1.jpg', '/images/img3.jpg', '/images/img1.jpg', '/images/img3.jpg'],
      vendor: {
        id: "102",
        name: "Apple",
        location: "Vijayawada",
        image: "/images/img1.jpg",
      },
    },
    {
      id: "7",
      name: "Mobile A",
      price: "$600",
      rating: 2.5,
      details: "Powered by the latest processor and backed with ample RAM.",
      reviews: ["Great product", "Good value for money"],
      description: "This smartphone is designed for those who demand performance and reliability. Powered by the latest processor and backed with ample RAM, it handles multitasking effortlessly. The vibrant display delivers crisp visuals, while the high-resolution camera captures stunning photos in any lighting condition. Whether you’re a gamer, a content creator, or just need a reliable device for daily use, this mobile phone is built to exceed expectations.",
      category: "Electronics",
      brand: "Brand A",
      inStock: true,
      image: "/images/img3.jpg",
      images: ['/images/img2.jpg', '/images/img1.jpg', '/images/img2.jpg', '/images/img1.jpg'],
      vendor: {
        id: "106",
        name: "Realme",
        location: "Khammam",
        image: "/images/img3.jpg",
      },
    },
    {
      id: "8",
      name: "Mobile B",
      price: "$700",
      rating: 5,
      details: "This smartphone is designed for those who demand performance and reliability.",
      reviews: ["Great product", "Good value for money"],
      description: "This smartphone is designed for those who demand performance and reliability. Powered by the latest processor and backed with ample RAM, it handles multitasking effortlessly. The vibrant display delivers crisp visuals, while the high-resolution camera captures stunning photos in any lighting condition. Whether you’re a gamer, a content creator, or just need a reliable device for daily use, this mobile phone is built to exceed expectations.",
      category: "Electronics",
      brand: "Brand A",
      inStock: false,
      image: "/images/img2.jpg",
      images: ['/images/img3.jpg', '/images/img2.jpg', '/images/img3.jpg', '/images/img2.jpg'],
      vendor: {
        id: "104",
        name: "Vivo",
        location: "Vizag",
        image: "/images/img2.jpg",
      },
    },
   
  ];

  /*export const mobiles = [
    {
      id: "1",
      image: "/images/img3.jpg",
      price: "$399",
      name: "Mobile B",
      description: "This is a description for Mobile B.",
    },
    {
      id: "2",
      image: "/images/img2.jpg",
      price: "$299",
      name: "Mobile A",
      description: "This is a description for Mobile A.",
    },
    {
      id: "3",
      image: "/images/img1.jpg",
      price: "$399",
      name: "Mobile C",
      description: "This is a description for Mobile B.",
    },
    {
      id: "4",
      image: "/images/img2.jpg",
      price: "$299",
      name: "Mobile A",
      description: "This is a description for Mobile A.",
    },
    {
      id: "5",
      image: "/images/img1.jpg",
      price: "$399",
      name: "Mobile B",
      description: "This is a description for Mobile B.",
    },
    {
      id: "6",
      image: "/images/img3.jpg",
      price: "$299",
      name: "Mobile C",
      description: "This is a description for Mobile A.",
    },
    {
      id: "7",
      image: "/images/img2.jpg",
      price: "$399",
      name: "Mobile B",
      description: "This is a description for Mobile B.",
    },
    {
      id: "8",
      image: "/images/img1.jpg",
      price: "$299",
      name: "Mobile A",
      description: "This is a description for Mobile A.",
    },
  ];*/